const page= document.querySelector("#site");
const navigationElement = createNavigation(navigation);
const heading = document.createElement("h1");
heading.textContent = calendar.title;
const schedulePage = document.createElement("section");
schedulePage.className = "schedule-page";
const calendarPanel = createCalendar(calendar.embedLink);
const calendarArea = document.createElement("div");
calendarArea.className = "schedule-calendar-area";
const largeHoneycomb = document.createElement("img");
largeHoneycomb.className = "schedule-honeycomb schedule-honeycomb--large";
largeHoneycomb.src = "../../assets/pinkspool.png";
largeHoneycomb.alt = "";
const smallHoneycomb = document.createElement("img");
smallHoneycomb.className = "schedule-honeycomb schedule-honeycomb--small";
smallHoneycomb.src = "../../assets/yellowspool.png";
smallHoneycomb.alt = "";
calendarArea.appendChild(calendarPanel);
calendarArea.appendChild(largeHoneycomb);
calendarArea.appendChild(smallHoneycomb);
page.appendChild(navigationElement);
page.appendChild(heading);
page.appendChild(calendarArea);